POST http://localhost:3001/api/storage/memory HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="image"; filename="love.webp"
Content-Type: image/jpeg

< ./love.webp
--boundary123--

###
GET http://localhost:3001/file-love-1739965880749.webp

###
POST http://localhost:3001/api/tracks HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "artist":{
        "name": "artist",
        "nickname": "nickname artist",
        "nationality": "spanish",
        "age": 22
    },
    "duration":{
        "start":1,
        "end": 2
    },
    "album":"album 2",
    "name": "song name",
    "cover": "https://es.wikipedia.org/wiki/Imagen"
}

###
GET http://localhost:3001/api/tracks/67c025f5e2b2929697d64998 HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

###

POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "name" : "Nombre",
    "age" : 2,
    "email": "sasa@gmail.com",
    "password": "1234",
    "role": "admin"
}

###
DELETE http://localhost:3001/api/tracks/67c8269973de437fde597d32


###
POST http://localhost:3001/api/auth/register
Content-Type: application/json
api_key: Api-publica-123

{
    "name" : "Nombre",
    "age" : 2,
    "email": "sasalara1@gmail.com",
    "password": "12345678"
}

###
POST http://localhost:3001/api/auth/login
Content-Type: application/json
api_key: Api-publica-123

{
    "email": "sasalara@gmail.com",
    "password": "12345678"
}

###
GET http://localhost:3001/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M4MzUyZDViZjhlN2E0NGY3MzYxZjUiLCJpYXQiOjE3NDEyNDg5MDUsImV4cCI6MTc0MTI1NjEwNX0.OvBhNao8nmpAPqiycCI7p8Lctb-3oGtrwbZw0kxccn0

###

// SI ESTÁ EXPIRADO: NOT_SESSION
GET http://localhost:3001/api/tracks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M4MzUyZDViZjhlN2E0NGY3MzYxZjUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQxMjUwNjExLCJleHAiOjE3NDEyNTc4MTF9.GQT5RZjS-6qbK1AG7K_fnY1CLtb-HMA8iDLiuEEGrmY


###
PUT http://localhost:3001/api/users/role/67c9691d9b8792eb0a9a6e4c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M4MzUyZDViZjhlN2E0NGY3MzYxZjUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQxMjUwNjExLCJleHAiOjE3NDEyNTc4MTF9.GQT5RZjS-6qbK1AG7K_fnY1CLtb-HMA8iDLiuEEGrmY

{
    "role": ["admin"]
}

###
POST http://localhost:3001/api/mail
Content-Type: application/json
api_key: Api-publica-123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RhYTQyYjc4MzUwNjNiN2MyMGExN2EiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQyMzgyMTMxLCJleHAiOjE3NDIzODkzMzF9.ieros-0ezrpmIRbHYXQZ6NFgj2N4FjSG9fXFepgA7tw

{
    "subject": "holi",
    "text": "holi buenas",
    "to": "saray.hershkovich@live.u-tad.com",
    "from": "hola@gmail.com"
}

